[package]
name = "discutils"
version = "0.0.0"
edition = "2021"
authors = ["RCW679"]
description = "A port of DiscUtils to Rust"
repository = "https://github.com/CixonInc/discutils-rs"
license = "MIT"

[dependencies]
